[workspace]
members = [
    "fxprof-processed-profile",
    "gecko_profile",
    "samply-api",
    "samply-symbols",
    "samply",
    "wholesym",
    "wholesym-addr2line",
    "tools/benchmarks",
    "tools/dump_table",
    "tools/query_api"
]
resolver = "2"
default-members = ["samply"]
