[package]
name = "etw-gecko"
version = "0.1.0"
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.53"
fxprof-processed-profile = { path = "../../samply/fxprof-processed-profile" }
uuid = "1" # We really want gecko_profile::debugid::uuid, but debugid doesn't re-export uuid
etw-reader = { path = "../etw-reader" }
pico-args = "0.4.2"
